### ISSUE TITLE
Broken hyper-link in "Basic Pkl/K8s Example"

### ISSUE THREAD

**Issue by andponlin-canva** [apple/pkl-k8s-examples#2]
Hello; on [this](https://github.com/apple/pkl-k8s-examples/blob/main/pkl/basic/README.adoc#basic-pkl-k8s-example) page there appears to be a broken link around the text to `io.k8s.convert`.

**Comment by stackoverflow** [comment]
Thanks @andponlin-canva for the report. The issue is fixed.
